#!/bin/bash

JAVA=$(which java)
if [ $? -eq 1 ]; then
  echo "Cannot find Java on your system."
  echo "See http://www.oracle.com/technetwork/java/javase/downloads/ to download the latest JDK."
  exit
fi

JAR="target/Puzzle.jar"
if [ ! -f ${JAR} ]; then
  echo "Cannot find ${JAR}."
  echo "Did you run 'script/build' first?" 
fi

${JAVA} -cp ${JAR} com.caseyscarborough.puzzle.Puzzle $@